import fs from 'fs';
import path from 'path';

export interface ReportData {
    timestamp: string;
    domain: string;
    duration: string;
    violations: any[];
    videoPath?: string;
    metadata: {
        userAgent: string;
        platform: string;
    };
}

export function generateAtlasReport(targetDir: string, data: ReportData) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const filename = 'report';

    // Video link (Assume it's already in the same folder)
    let finalVideoLink = 'N/A';
    if (data.videoPath) {
        const videoName = path.basename(data.videoPath);
        finalVideoLink = `[${videoName}](${videoName})`;
    }

    // 1. JSON Export
    const jsonPath = path.join(targetDir, `${filename}.json`);
    fs.writeFileSync(jsonPath, JSON.stringify(data, null, 2));

    // 2. Human Readable Markdown summary
    const mdPath = path.join(targetDir, `${filename}.md`);
    const mdContent = `
# 🛠️ Atlas Audit Report
**Date:** ${new Date().toLocaleString()}
**Domain:** ${data.domain}
**Session Duration:** ${data.duration}

---

## 🛡️ Violations Found (${data.violations.length})
${data.violations.length === 0 ? '_No critical violations found._' : ''}

${data.violations.map(v => `
### [${v.severity === 2 ? '🔴 ERROR' : '🟡 WARN'}] ${v.type}
> ${v.message}
_Found at: ${v.time || 'N/A'}_
`).join('\n')}

---

## 📹 Session Recording
**Video Path:** ${finalVideoLink}

---

## 💻 Environment
- **Platform:** ${data.metadata.platform}
- **User Agent:** ${data.metadata.userAgent}

---
_Generated by Atlas Audit Engine_
`;

    fs.writeFileSync(mdPath, mdContent);

    console.log(`\n[Atlas] ✅ Report Generated: ${path.relative(targetDir, mdPath)}`);
    return { jsonPath, mdPath };

}
